//
//  FamilyIDs.swift
//  Kalvian Roots
//
//  Hybrid array/set--Array for order + Set for O(1) lookups
//
//  Created by Michael Bendio on 7/11/25.
//

import Foundation

// Family IDs in Juuret Kalvialla
struct FamilyIDs {
    static let validFamilyIds: [String] = [
        "HERLEVI 1", "HERLEVI 2", "HERLEVI 3", "HERLEVI 4",
        "HERLEVI 5", "HERLEVI 6", "HERLEVI 7", "HERLEVI 8",
        "HERLEVI 9", "HERLEVI 10", "HERLEVI 11", "HERLEVI II 1",
        "HERLEVI II 2", "HERLEVI II 3", "HERLEVI II 4", "HERLEVI II 5",
        "HERLEVI II 6", "HERLEVI II 7", "HERLEVI II 8", "HERLEVI II 9",
        "HERLEVI II 10", "HERLEVI II 11", "HERLEVI II 12", "HERLEVI II 13",
        "VIDENOJA 1", "VIDENOJA 2", "VIDENOJA 3", "VIDENOJA 4",
        "VIDENOJA 5", "VIDENOJA 6", "VIDENOJA 7", "VIDENOJA 8",
        "VIDENOJA 9", "VIDENOJA 10", "VÄHÄLÄ 1", "VÄHÄLÄ 2",
        "VÄHÄLÄ 3", "VÄHÄLÄ 4", "VÄHÄLÄ 5", "VÄHÄLÄ 6",
        "VÄHÄLÄ 7", "VÄHÄLÄ 8", "VÄHÄLÄ 9", "VÄHÄLÄ 10",
        "VÄHÄLÄ 11", "VÄHÄLÄ II 1", "VÄHÄLÄ II 2", "VÄHÄLÄ II 3",
        "VÄHÄLÄ II 4", "VÄHÄLÄ II 5", "VÄHÄLÄ II 6", "YLI-VÄHÄLÄ 1",
        "RAHKONEN 1", "RAHKONEN 2", "RAHKONEN 3", "RAHKONEN 4",
        "RAHKONEN 5", "RAHKONEN 6", "RAHKONEN 7", "RAHKONEN 8",
        "RAHKONEN 9", "RAHKONEN 10", "RAHKONEN 11", "RAHKONEN 12",
        "RAHKONEN 13", "LÄNTTÄ 1", "LÄNTTÄ 2", "LÄNTTÄ 3",
        "LÄNTTÄ 4", "LÄNTTÄ 5", "LÄNTTÄ 6", "LÄNTTÄ 7",
        "LÄNTTÄ 8", "LÄNTTÄ 9", "LÄNTTÄ 10", "LÄNTTÄ 11",
        "LÄNTTÄ 12", "LÄNTTÄ 13", "LÄNTTÄ 14", "SIKALA 1",
        "SIKALA 2", "SIKALA 3", "SIKALA 4", "SIKALA 5",
        "SIKALA 6", "SIKALA 7", "SIKALA 8", "SIKALA 9",
        "SIKALA 10", "SIKALA II 1", "SIKALA II 2", "SIKALA II 3",
        "SIKALA II 4", "SIKALA II 5", "SIKALA II 6", "SIKALA II 7",
        "PIENI SIKALA 1", "PIENI SIKALA 2", "PIENI SIKALA 3", "JÄÄSKÄ 1",
        "JÄÄSKÄ 2", "JÄÄSKÄ 3", "JÄÄSKÄ 4", "JÄÄSKÄ 5",
        "JÄÄSKÄ 6", "JÄÄSKÄ 7", "JÄÄSKÄ 8", "JÄÄSKÄ 9",
        "JÄÄSKÄ 10", "JÄÄSKÄ 11", "JÄÄSKÄ 12", "JÄÄSKÄ 13",
        "JÄÄSKÄ 14", "KORPI 1", "KORPI 2", "KORPI 3",
        "KORPI 4", "KORPI 5", "KORPI 6", "KORPI 7",
        "KORPI 8", "KORPI 9", "KORPI 10", "KORPI 11",
        "KORPI 12", "HANHISALO 1", "HANHISALO 2", "HANHISALO 3",
        "HANHISALO 4", "HANHISALO 5", "HANHISALO 6", "HANHISALO 7",
        "HANHISALO 8", "HANHISALO 9", "HANHISALO 10", "HANHISALO 11",
        "HANHISALO II 1", "HANHISALO II 2", "HANHISALO II 3", "HANHISALO III 1",
        "HANHISALO III 2", "HANHISALO III 3", "ASMUND 1", "ASMUND 2",
        "ASMUND 3", "ASMUND 4", "ASMUND 5", "ASMUND 6",
        "ASMUND 7", "ASMUND 8", "ASMUND 9", "ASMUND 10",
        "ASMUND 11", "ASMUND 12", "ASMUND 13", "ASMUND 14",
        "HAAPANIEMI 1", "HAAPANIEMI 2", "HAAPANIEMI 3", "HAAPANIEMI 4",
        "HAAPANIEMI 5", "HAAPALA 6", "HAAPALA 7", "HAAPALA II 1",
        "HAAPALA II 2", "HAAPALA II 3", "HAAPASALO 1", "HAAPASALO 2",
        "HAAPASALO 3", "HAAPASALO 4", "NORPPA 1", "NORPPA 2",
        "NORPPA 3", "NORPPA 4", "NORPPA 5", "NORPPA 6",
        "NORPPA 7", "NORPPA 8", "NORPPA II 1", "NORPPA II 2",
        "NORPPA II 3", "JÄNESNIEMI 1", "JÄNESNIEMI 2", "JÄNESNIEMI 3",
        "JÄNESNIEMI 4", "JÄNESNIEMI 5", "JÄNESNIEMI 6", "JÄNESNIEMI 7",
        "JÄNESNIEMI 8", "JÄNESNIEMI 9", "ISOMAA 1", "KORVELA 2",
        "KORVELA 3", "KORVELA 4", "AHOKANGAS 1", "AHOKANGAS 2",
        "AHOKANGAS 3", "AHOKANGAS 4", "AHOKANGAS 5", "NÄVERBACKA 1",
        "NÄVERBACKA 2", "NÄVERBACKA 3", "KALLINKI 1", "KALLINKI 2",
        "KALLINKI 3", "KALLINKI 4", "KALLINKI 5", "KALLINKI 6",
        "HONKALA 0", "HONKALA 1", "HONKALA 2", "NISKALA 1",
        "RUOKOJA 1", "RUOKOJA 2", "RUOKOJA 3", "RUOKOJA 4",
        "RUOKOJA 5", "RUOKOJA 6", "RUOKOJA 7", "RUOKOJA 8",
        "RUOKOJA 9", "RUOKOJA 10", "RIMPIOJA 1", "RIMPIOJA 2",
        "RIMPIOJA 3", "RIMPIOJA 4", "RIMPIOJA 5", "RIMPIOJA 6",
        "RIMPIOJA 7", "RIMPILÄ 1", "RIMPILÄ 2", "RIMPILÄ 3",
        "RIMPILÄ 4", "RIMPILÄ 5", "RIMPILÄ 6", "RIMPILÄ 7",
        "RIMPILÄ 8", "RIMPILÄ 9", "RIMPILÄ 10", "RIMPILÄ 11",
        "MAUNULA 1", "MAUNULA 2", "MAUNULA 3", "MAUNULA 4",
        "MAUNULA 5", "MAUNULA 6", "MAUNULA 7", "MAUNULA 8",
        "MAUNULA 9", "MAUNULA 10", "MAUNULA 11", "MAUNULA 12",
        "MAUNULA II 1", "MAUNULA II 2", "MAUNULA II 3", "MAUNULA II 4",
        "RUOKOJA II 1", "RUOKOJA II 2", "RUOKOJA II 3", "RUOKOJA II 4",
        "RUOKOJA II 5", "RUOKOJA II 6", "RUOKOJA II 7", "RUOKOJA II 8",
        "PAJALA 1", "PAJALA 2", "PAJALA 3", "PAJALA 4",
        "PAJALA 5", "PAJALA 6", "PAJALA 7", "HILLI 1",
        "HILLI 2", "HILLI 3", "HILLI 4", "HILLI 5",
        "HILLI 6", "HILLI 7", "HILLI 8", "HILLI II 1",
        "HILLI II 2", "HILLI II 3", "LASSILA 1", "LASSILA 2",
        "LASSILA 3", "LASSILA 4", "LASSILA 5", "LASSILA 6",
        "LASSILA 7", "LASSILA 8", "LASSILA 9", "LASSILA 10",
        "LASSILA 11", "LASSILA 12", "LASSILA 13", "LASSILA II 1",
        "LASSILA II 2", "LASSILA II 3", "LASSILA II 4", "LASSILA III 1",
        "LASSILA III 2", "LASSILA III 3", "LASSILA III 4", "LASSILA III 5",
        "LASSILA IV 1", "LASSILA IV 2", "NISSI 1", "NISSI 2",
        "NISSI 3", "NISSI 4", "NISSI 5", "NISSI 6",
        "NISSI 7", "NISSI 8", "NISSI 9", "NISSI 10",
        "NISSI 11", "NISSI 12", "NISSI 13", "NISSI 14",
        "NISSI 15", "NISSI 16", "NISSI II 1", "NISSI II 2",
        "NISSI II 3", "MIEKKOJA III 1", "MIEKKOJA III 2", "MIEKKOJA III 3",
        "MIEKKOJA III 4", "MIEKKOJA III 5", "MIEKKOJA III 6", "MIEKKOJA III 7",
        "MIEKKOJA 1", "MIEKKOJA 1B", "MIEKKOJA 2", "MIEKKOJA 3",
        "MIEKKOJA 4", "MIEKKOJA 5", "MIEKKOJA 6", "MIEKKOJA 7",
        "MIEKKOJA 8", "MIEKKOJA 9", "MIEKKOJA II 1", "MIEKKOJA II 2",
        "MIEKKOJA II 3", "MIEKKOJA II 4A", "MIEKKOJA II 4B", "MIEKKOJA II 5",
        "MIEKKOJA II 6", "MIEKKOJA II 7", "MIEKKOJA II 8", "MIEKKOJA II 8B",
        "MIEKKOJA II 9", "MIEKKOJA II 10", "MIEKKOJA II 11", "MIEKKOJA II 12",
        "MIEKKOJA II 13", "MIEKKOJA II 14", "TUOMAALA 1", "TUOMAALA 2",
        "TUOMAALA 3", "TUOMAALA 4", "TUOMAALA 5", "TUOMAALA 6",
        "TUOMAALA 7", "TUOMAALA 8", "TUOMAALA 9", "TUOMAALA 10",
        "TUOMAALA 11", "TUOMAALA II 1", "TUOMAALA II 2", "TUOMAALA II 3",
        "TUOMAALA II 4", "TUOMAALA II 6", "TUOMAALA II 7", "TUOMAALA II 8",
        "TUOMAALA II 9", "TUOMAALA II 10", "VÄHÄJOKI 1", "VÄHÄJOKI/OLLILA 2",
        "OLLILA/TIKANOJA 3", "TIKANOJA 4", "TIKANOJA 5", "TIKANOJA 6",
        "TIKANOJA 7", "TIKANOJA 8", "TIKANOJA 9", "TIKANOJA 10",
        "PUUKANGAS 1", "PUUKANGAS 2", "PUUKANGAS 3", "PUUKANGAS 4",
        "PUUKANGAS 5", "PUUKANGAS 6", "PUUKANGAS 7", "HANGASKANGAS 1",
        "HANGASKANGAS 2", "HANGASKANGAS 3", "HANGASKANGAS 4", "HANGASKANGAS 5",
        "HANGASKANGAS 6", "HANGASKANGAS 7", "HANGASKANGAS 8", "HANGASKANGAS 9",
        "HANGASKANGAS 10", "HANGASKANGAS 11", "HANGASKANGAS 12", "HANGASKANGAS 13",
        "SAARALA 1", "SAARALA 2", "SAARALA 3", "SAARALA 4",
        "SAARALA 5", "SAARALA 6", "SAARALA 7", "SAARALA 8",
        "SAARALA 9", "SAARALA 10", "SAARALA 11", "SAARALA 12",
        "SAARALA 13", "SAARALA 14", "SAARALA 15", "SAARALA 16",
        "SAARALA 17", "PASSOJA 1", "PASSOJA 2", "PASSOJA 3",
        "PASSOJA 4", "PASSOJA 5", "ISO-PASSOJA 6", "ISO-PASSOJA 7",
        "ISO-PASSOJA 8", "ISO-PASSOJA 9", "ISO-PASSOJA 10", "ISO-PASSOJA II 1",
        "ISO-PASSOJA II 2", "ISO-PASSOJA II 3", "ISO-PASSOJA II 4", "ISO-PASSOJA II 5",
        "ISO-PASSOJA II 6", "ISO-PASSOJA II 7", "ISO-PASSOJA III 1", "ISO-PASSOJA III 2",
        "ISO-PASSOJA III 3", "ISO-PASSOJA III 4", "PIENI PASSOJA 1", "PIENI PASSOJA 2",
        "PIENI PASSOJA 3", "PIENI PASSOJA 4", "PIENI PASSOJA 5", "PIENI PASSOJA 6",
        "PIENI PASSOJA 7", "PIENI PASSOJA 8", "PIENI PASSOJA 9", "HONKIMAA 1",
        "HONKIMAA 1B", "HONKIMAA 1C", "HONKIMAA 2", "HONKIMAA 3",
        "HONKIMAA 4", "HONKIMAA 5", "HONKIMAA 6", "HONKIMAA 7",
        "HONKIMAA 8", "HONKIMAA 9", "HONKIMAA II 1", "HONKIMAA II 2",
        "HONKIMAA II 3", "MYLLYKANGAS 1", "MYLLYKANGAS 2", "MYLLYKANGAS 3",
        "MYLLYKANGAS 4", "MYLLYKANGAS 5", "MYLLYKANGAS 6", "SALTBACKA 1",
        "SALTBACKA 2", "SALTBACKA 3", "SALTBACKA 4", "HONKALA 3",
        "HONKALA 4", "HONKALA 5", "HONKALA 6", "TIKKANEN 1",
        "TIKKANEN 2", "TIKKANEN 3", "TIKKANEN 4", "TIKKANEN 6",
        "TIKKANEN 7", "TIKKANEN 8", "TIKKANEN 9", "TIKKANEN 10",
        "TIKKANEN 11", "TIKKANEN 12", "TIKKANEN 13", "TIKKANEN 14",
        "TIKKANEN 15", "TIKKANEN 16", "TIKKANEN II 1", "TIKKANEN II 2",
        "TIKKANEN II 3", "TIKKANEN II 4", "KORPIJÄRVI 1", "KORPIJÄRVI 2",
        "KORPIJÄRVI 3", "KORPIJÄRVI 4", "KORPIJÄRVI 5", "KORPIJÄRVI 6",
        "KORPIJÄRVI 7", "KORPIJÄRVI 8", "KORPIJÄRVI 9", "KORPIJÄRVI 10",
        "KORPIJÄRVI 11", "KORPIJÄRVI 12", "KORPIJÄRVI 13", "KORPIJÄRVI II 1",
        "KORPIJÄRVI II 2", "KLEEMOLA 1", "KLEEMOLA 2", "KLEEMOLA 3",
        "KLEEMOLA 4", "KLEEMOLA 5", "KLEEMOLA 6", "KLEEMOLA 7",
        "KLEEMOLA 8", "KLEEMOLA 9", "KLEEMOLA 10", "KLEEMOLA 11",
        "KLEEMOLA 12", "KLEEMOLA 13", "KLEEMOLA 14", "KLEEMOLA 15",
        "KLEEMOLA 16", "KLEEMOLA II 1", "KLEEMOLA II 2", "KLEEMOLA II 3",
        "KLEEMOLA II 4", "KLEEMOLA II 5", "KLEEMOLA II 6", "KYKYRI 1",
        "KYKYRI 2", "KYKYRI 3", "KYKYRI 4", "KYKYRI 5",
        "KYKYRI 6", "KYKYRI 7", "KYKYRI 8", "KYKYRI 9",
        "KYKYRI 10", "KYKYRI 11", "KYKYRI 12", "KYKYRI 13",
        "KYKYRI II 1", "KYKYRI II 2", "KYKYRI II 3", "KYKYRI II 4",
        "KYKYRI II 5", "KYKYRI II 6", "KYKYRI II 7", "KYKYRI II 8",
        "KYKYRI II 9", "SAKERI 1", "SAKERI 2", "SAKERI 3",
        "SAKERI 4", "SAKERI 5", "SAKERI 6", "SAKERI 7",
        "SAKERI 8", "SAKERI 9", "PIENI-PORKOLA 1", "PIENI-PORKOLA 2",
        "PIENI-PORKOLA 3", "PIENI-PORKOLA 4", "PIENI-PORKOLA 5", "PIENI-PORKOLA 6",
        "PIENI-PORKOLA 7", "PIENI-PORKOLA 8", "PIENI-PORKOLA 9", "PIENI-PORKOLA 10",
        "PIENI-PORKOLA 11", "MÄKI-PORKOLA 12", "MÄKELÄ 13", "MÄKELÄ 14",
        "MÄKELÄ 15", "MÄKELÄ 16", "PORKOLA 1", "PORKOLA 2",
        "PORKOLA 3", "PORKOLA 4", "PORKOLA 5", "ISO-PORKOLA 6",
        "ISO-PORKOLA 7", "ISO-PORKOLA 8", "ISO-PORKOLA 9", "ISO-PORKOLA 10",
        "ISO-PORKOLA 11", "ISO-PORKOLA 12", "NURILA 1", "NURILA 2",
        "NURILA 3", "NURILA 4", "NURILA 5", "NURILA 6",
        "NURILA 7", "NURILA 8", "NURILA 9", "NURILA 10",
        "NURILA 11", "NURILA 12", "NURILA 13", "NURILA 14",
        "NURILA 15", "PIRKOLA 1", "PIRKOLA 2", "PIRKOLA 3",
        "PIRKOLA 4", "PIRKOLA 5", "SUONPERÄ 6", "PIRKOLA 6",
        "PIRKOLA 7", "PIRKOLA 8", "PIRKOLA 9", "PIRKOLA 10",
        "PIRKOLA II 1", "PIRKOLA II 2", "PIRKOLA II 3", "PIRKOLA II 4",
        "PIRKOLA II 5", "TUUNALA 1", "TUUNALA 2", "TUUNALA 3",
        "TUUNALA 4", "TUUNALA 5", "TUUNALA 6", "TUUNALA 7",
        "TUUNALA 8", "TUUNALA 9", "TUUNALA 10", "TUUNALA 11",
        "TUUNALA 12", "TUUNALA 13", "TUUNALA 14", "TUUNALA 15",
        "TUUNALA 16", "TUUNALA 17", "TUUNALA 18", "TUUNALA 19",
        "TUUNALA 20", "TUUNALA 21", "TUUNALA 22", "TUUNALA 23",
        "VÄÄPELI 1", "VÄÄPELI 2", "VÄÄPELI 3", "VÄÄPELI 4",
        "VÄÄPELI 5", "HIETAPÖLKKI 1", "HIETAPÖLKKI 2", "HIETAPÖLKKI 3",
        "HIETAPÖLKKI 4", "HIETALA 5", "HIETALA 6", "HIETALA 7",
        "HIETALA 8", "HIETALA 9", "HERRONEN 1", "HERRONEN 2",
        "HERRONEN 3", "HERRONEN 4", "HERRONEN 5", "HERRONEN 6",
        "HERRONEN 7", "HERRONEN 8", "HERRONEN 9", "HERRONEN 10",
        "HERRONEN 11", "HERRONEN II 1", "HERRONEN II 2", "HERRONEN II 3",
        "HERRONEN II 4", "HERRONEN II 5", "RITA 1", "RITA 2",
        "RITA 3", "RITA 4", "RITA 5", "RITA 6", "RITA 7",
        "RITA 8", "RITA 9", "RITA 10", "RITA 11",
        "RITA II 1", "RITA II 2", "RITA II 3", "RITA II 4",
        "RITA II 5", "RITA II 6", "RITA II 7", "HASSINEN 1",
        "HASSINEN 2", "HASSINEN 3", "HASSINEN 4", "HASSINEN 5",
        "HASSINEN 6", "HASSINEN 7", "HASSINEN 8", "HASSINEN 9",
        "HASSINEN 10", "HASSINEN 11", "HASSINEN 12", "HASSINEN 13",
        "HASSINEN 14", "LAXO 1", "LAXO 2", "LAXO 3",
        "LAXO 4", "LAXO 5", "LAXO 6", "LAXO 7",
        "LAXO 8", "HUHTALA 1", "HUHTALA 2", "HUHTALA 3",
        "HUHTALA 4", "HUHTALA 5", "VUOLLE 1", "VUOLLE 2",
        "VUOLLE 3", "VUOLLE 4", "VUOLLE 5", "VUOLLE 6",
        "VUOLLE 7", "VUOLLE 8", "VUOLLE 9", "VUOLLE 10",
        "VUOLLE 11", "VUOLLE 12", "VUOLLE 13", "VUOLLE 14",
        "VUOLLE 15", "VUOLLE 16", "VUOLLE 17", "VUOLLE II 1",
        "VUOLLE II 2", "VUOLLE II 3", "VUOLLE II 4", "VUOLLE II 5",
        "VUOLLE II 6", "VUOLLE II 7", "VUOLLE II 8", "VUOLLE III 1",
        "VUOLLE III 2", "VUOLLE III 3", "VUOLLE III 4", "VUOLLE III 5",
        "VUOLLE III 6", "SALO 1", "SALO 2", "L. VUOLLE 1",
        "L. VUOLLE 2", "L. VUOLLE 3", "L.VUOLLE 4", "L. VUOLLE 5",
        "L. VUOLLE 6", "L. VUOLLE 7", "L. VUOLLE 8", "L. VUOLLE 9",
        "L. VUOLLE 10", "L. VUOLLE II 1", "L. VUOLLE II 2", "VUOLTEEN TORPPA 1",
        "L. VUOLLE II 3", "L. VUOLLE II 4", "L. VUOLLE II 5", "L. VUOLLE III 1",
        "L. VUOLLE III 2", "L. VUOLLE III 3", "L. VUOLLE III 4", "PERNU 1",
        "PERNU 2", "PERNU 3", "PERNU 4", "PERNU 5",
        "PERNU 6", "PERNU 7", "PERNU 8", "PERNU 9",
        "PERNU 10", "PERNU 11", "PERNU 12", "PERNU 13",
        "PERNU 14", "PERNU 15", "PERNU 16", "PERNU 17",
        "PERNU 18", "PERNU 19", "PERNU 20", "PERNU 21",
        "PERNU 22", "MARTTILA 1", "MARTTILA 2", "MARTTILA 3",
        "MARTTILA 4", "MARTTILA 5", "MARTTILA 6", "MARTTILA 7",
        "MARTTILA 8", "MARTTILA 9", "MARTTILA 10", "MARTTILA 11",
        "MARTTILA 12", "MARTTILA 13", "RANTA-MARTTILA 1", "RANTA-MARTTILA 2",
        "RANTA-MARTTILA 3", "RANTA-MARTTILA 4", "MARTTILA II 1", "MARTTILA II 2",
        "MARTTILA II 3", "MARTTILA II 4", "MARTTILA II 5", "MARTTILA II 6",
        "MARTTILA II 7", "MARTTILA II 8", "MARTTILA II 9", "MARTTILA II 10",
        "MARTTILA III 1", "MARTTILA III 2", "MARTTILA III 3", "MARTTILA III 4",
        "MARTTILA III 5", "PENTTILÄ 1", "PENTTILÄ 2", "PENTTILÄ 3",
        "PENTTILÄ 4", "PENTTILÄ 5", "PENTTILÄ 6", "PENTTILÄ 7",
        "PENTTILÄ 8", "PENTTILÄ 9", "PENTTILÄ 10", "PENTTILÄ II 1",
        "PENTTILÄ II 2", "PIKKU-PENTTILÄ II 3", "PIKKU-PENTTILÄ II 4", "HYYPPÄ 1",
        "HYYPPÄ 2", "HYYPPÄ 3", "HYYPPÄ 4", "HYYPPÄ 5",
        "HYYPPÄ 6", "ISO-HYYPPÄ 7", "ISO-HYYPPÄ 8", "ISO-HYYPPÄ 9",
        "ISO-HYYPPÄ 10", "ISO-HYYPPÄ 11", "MIKKOLA 1", "MIKKOLA 2",
        "MIKKOLA 3", "MIKKOLA 4", "MIKKOLA 5", "MIKKOLA 6",
        "MIKKOLA 7", "MIKKOLA 8", "MIKKOLA 9", "MIKKOLA 10",
        "MIKKOLA 11", "MIKKOLA 12", "MIKKOLA 13", "MIKKOLA 14",
        "VÄHÄ-HYYPPÄ 1", "VÄHÄ-HYYPPÄ 2", "VÄHÄ-HYYPPÄ 3", "VÄHÄ-HYYPPÄ 4",
        "VÄHÄ-HYYPPÄ 5", "VÄHÄ-HYYPPÄ 6", "VÄHÄ-HYYPPÄ 7", "VÄHÄ-HYYPPÄ 8",
        "MAUNUMÄKI 1", "MAUNUMÄKI 2", "MAUNUMÄKI 3", "MAUNUMÄKI 4",
        "MAUNUMÄKI 5", "MAUNUMÄKI 6", "MAUNUMÄKI 7", "MAUNUMÄKI 8",
        "MAUNUMÄKI 9", "MAUNUMÄKI 10", "MAUNUMÄKI II 1", "MAUNUMÄKI II 2",
        "MAUNUMÄKI II 3", "MAUNUMÄKI III 1", "MAUNUMÄKI III 2", "MAUNUMÄKI III 3",
        "MAUNUMÄKI III 4", "MAUNUMÄKI III 5", "MAUNUMÄKI III 6", "MAUNUMÄKI IV 1",
        "MAUNUMÄKI IV 2", "MAUNUMÄKI IV 3", "MAUNUMÄKI IV 4", "MAUNUMÄKI IV 5",
        "MAUNUMÄKI IV 6", "MAUNUMÄKI IV 7", "KOURIJÄRVI 1", "KOURIJÄRVI 2",
        "KOURIJÄRVI 3", "KOURIJÄRVI 4", "KOURIJÄRVI 5", "KOURIJÄRVI 6",
        "KOURIJÄRVI 7", "KOURIJÄRVI 8", "KOURIJÄRVI 9", "KOURIJÄRVI 10",
        "KOURIJÄRVI 11", "KOURIJÄRVI 12", "KOURIJÄRVI 13", "KOURIJÄRVI 14",
        "SIIRILÄ 1", "SIIRILÄ 2", "SIIRILÄ 3", "SIIRILÄ 4",
        "SIIRILÄ 5", "SIIRILÄ 6", "SIIRILÄ 7", "SIIRILÄ 8",
        "SIIRILÄ 9", "SIIRILÄ 10", "SIIRILÄ 11", "SIIRILÄ 12",
        "KOSKI 1", "KOSKI 2", "KOSKI 3", "KOSKI 4",
        "KOSKI 5", "KOSKI 6", "KOSKI 7", "KOSKI 8",
        "KOSKI 9", "KOSKI II 1", "KOSKI II 2", "KOSKI II 3",
        "RIIHIMÄKI 1", "RIIHIMÄKI 2", "RIIHIMÄKI 3", "RIIHIMÄKI 4",
        "RIIHIMÄKI 5", "RIIHIMÄKI 6", "RIIHIMÄKI 7", "RIIHIMÄKI 8",
        "RIIHIMÄKI 9", "ASUJAMAA 1", "ASUJAMAA 2", "ASUJAMAA 3",
        "ASUJAMAA 4", "ASUJAMAA 5", "ASUJAMAA 6", "ASUJAMAA 7",
        "ASUJAMAA 8", "ASUJAMAA 9", "SYVÄJÄRVI 1", "SYVÄJÄRVI 2",
        "SYVÄJÄRVI 3", "SYVÄJÄRVI 4", "SYVÄJÄRVI 5", "SYVÄJÄRVI 6",
        "SYVÄJÄRVI 7", "SYVÄJÄRVI II 1", "SYVÄJÄRVI II 2", "SYVÄJÄRVI II 3",
        "SYVÄJÄRVI II 4", "KARHUNOJA 2", "KARHUNOJA 3", "KARHUNOJA 4",
        "KARHUNOJA 5", "KARHUNOJA II 1", "KARHUNOJA II 2", "KARHUNOJA II 3",
        "KARHUNOJA II 4", "KARHUNOJA II 5", "KARHUNOJA III 1", "KARHUNOJA III 2",
        "KARHUNOJA III 3", "KARHUNOJA III 4", "KARHUNOJA III 5", "KARHUNOJA III 6",
        "KUMPULA 1", "KUMPULA 2", "KUMPALA 3", "KUMPULA 4",
        "KUMPULA 5", "KUMPULA 6", "KUMPULA 7", "KUMPULA 8",
        "PAPPILAN 1", "PUUHKALA 1", "LUKKARI 1", "LUKKARI 2",
        "LUKKARI 3", "SIMUKKALA 1", "SIMUKKALA 2", "SIMUKKALA 3",
        "SIMUKKALA 4", "SIMUKKALA 5", "SIMUKKALA 6", "SIMUKKALA 7",
        "SIMUKKALA 8", "SIMUKKALA 9", "INGALSUO 1", "INGALSUO 2",
        "INGALSUO 3", "INGALSUO 4", "INGALSUO 6", "INGALSUO 7",
        "INGALSUO 8", "INGALSUO 9", "INGALSUO 10", "INGALSUO 11",
        "INGALSUO 12", "INGALSUO 13", "INGALSUO 14", "INGALSUO II 1",
        "INGALSUO II 2", "INGALSUO II 3", "INGALSUO II 4", "INGALSUO II 5",
        "INGALSUO II 6", "KIPPO 1", "KIPPO 2", "KIPPO 3",
        "KIPPO 4", "KIPPO 5", "KIPPO 6", "KIPPO 7",
        "KIPPO 8", "KIPPO 9", "KIPPO 10", "KIPPO 11",
        "KIPPO II 1", "KIPPO II 2", "KIPPO II 3", "KARHULAHTI 1",
        "KARHULAHTI 2", "KARHULAHTI 3", "KARHULAHTI 3A", "KARHULAHTI 3B",
        "KARHULAHTI 4", "KARHULAHTI 5", "KARHULAHTI 6", "KARHULAHTI 7",
        "KARHULAHTI 8", "KARHULAHTI 9", "KARHULAHTI 10", "KARHULAHTI 11",
        "KARHULAHTI 12", "KARHULAHTI 13", "KARHULAHTI II 1", "KARHULAHTI II 2",
        "KARHULAHTI II 3", "KARHULAHTI II 4", "KARHULAHTI III 1", "KARHULAHTI III 2",
        "KARHULAHTI III 3", "KARHULAHTI III 4", "KARHULAHTI III 5", "KINNARI 1",
        "KINNARI 2", "KINNARI 3", "KINNARI 4", "KINNARI 5",
        "KINNARI 6", "KINNARI 7", "KINNARI 8", "KINNARI 9",
        "KINNARI 10", "KINNARI 11", "KINNARI 12", "PIETILÄ 1",
        "PIETILÄ 2", "PIETILÄ 3", "PIETILÄ 4", "PIETILÄ 5",
        "PIETILÄ 6", "PIETILÄ 7", "PIETILÄ 8", "PIETILÄ 9",
        "PIETILÄ 10", "PIETILÄ 11", "PIETILÄ 12", "PIETILÄ 13",
        "PIETILÄ 14", "PIETILÄ II 1", "PIETILÄ II 2", "PIETILÄ II 3",
        "PIETILÄ II 4", "MATTJUSS 1", "MATTJUSS 2", "MATTJUSS 3",
        "MATTJUSS 4", "MATTJUSS 5", "MATTJUSS 6", "MATINJUSSI 7",
        "MATINJUSSI 8", "MATTJUSSI 9", "MATINJUSSI 10", "MATINJUSSI 11",
        "MATINJUSSI 12", "MATTJUSS II 1", "MATINJUSSI II 2", "MATINJUSSI II 3",
        "MATINJUSSI II 4", "NISSILÄ 1", "NISSILÄ 2", "NISSILÄ 3",
        "NISSILÄ 4", "NISSILÄ 5", "NISSILÄ 6", "NISSILÄ 7",
        "NISSILÄ 8", "NISSILÄ 9", "NISSILÄ 10", "NISSILÄ II 1",
        "NISSILÄ II 2", "NISSILÄ II 3", "NISSILÄ III 1", "NISSILÄ III 2",
        "NISSILÄ III 3", "ISO-PEITSO 1", "ISO-PEITSO 2", "ISO-PEITSO 3",
        "ISO-PEITSO 4", "ISO-PEITSO 5", "ISO-PEITSO 6", "ISO-PEITSO 7",
        "ISO-PEITSO 8", "ISO-PEITSO 9", "ISO-PEITSO 10", "ISO-PEITSO 11",
        "ISO-PEITSO 12", "ISO-PEITSO II 1", "ISO-PEITSO II 2", "ISO-PEITSO II 3",
        "ISO-PEITSO II 4", "ISO-PEITSO II 5", "ISO-PEITSO II 6", "ISO-PEITSO II 7",
        "ISO-PEITSO III 1", "ISO-PEITSO III 2", "ISO-PEITSO III 3", "ISO-PEITSO III 4",
        "VÄHÄ-PEITSO 1", "VÄHÄ-PEITSO 2", "VÄHÄ-PEITSO 3", "VÄHÄ-PEITSO 4",
        "VÄHÄ-PEITSO 5", "VÄHÄ-PEITSO 6", "VÄHÄ-PEITSO 7", "VÄHÄ-PEITSO 8",
        "VÄHÄ-PEITSO 9", "VÄHÄ-PEITSO 10", "VÄHÄ-PEITSO 11", "VÄHÄ-PEITSO 12",
        "VÄHÄ-PEITSO II 1", "VÄHÄ-PEITSO II 2", "VÄHÄ-PEITSO II 3", "VÄHÄ-PEITSO II 4",
        "VÄHÄ-PEITSO II 5", "VÄHÄ-HAKUNTI 1", "VÄHÄ-HAKUNTI 2", "VÄHÄ-HAKUNTI 3",
        "VÄHÄ-HAKUNTI 4", "VÄHÄ-HAKUNTI 5", "VÄHÄ-HAKUNTI 6", "VÄHÄ-HAKUNTI 7",
        "VÄHÄ-HAKUNTI 9", "VÄHÄ-HAKUNTI 10", "VÄHÄ-HAKUNTI 11", "VÄHÄ-HAKUNTI II 1",
        "VÄHÄ-HAKUNTI II 2", "VÄHÄ-HAKUNTI II 3", "VÄHÄ-HAKUNTI II 4", "ISO-HAKUNTI 1",
        "ISO-HAKUNTI 2", "ISO-HAKUNTI 3", "ISO-HAKUNTI 4", "ISO-HAKUNTI 5",
        "ISO-HAKUNTI 6", "ISO-HAKUNTI 7", "ISO-HAKUNTI 8", "ISO-HAKUNTI 9",
        "ISO-HAKUNTI 10", "ISO-HAKUNTI 11", "ISO-HAKUNTI 12", "ISO-HAKUNTI 13",
        "PELTTARI 1", "PELTTARI 2", "PELTTARI 3", "PELTTARI 4",
        "PELTTARI 5", "PELTTARI 6", "PELTTARI 7", "PELTTARI 8",
        "PELTTARI 9", "PELTTARI 10", "PELTTARI 11", "PELTTARI 12",
        "PELTTARI 13", "VALKAMAA 1", "VALKAMAA 2", "VALKAMAA 3",
        "VALKAMAA 4", "VALKAMAA 5", "VALKAMAA 6", "VALKAMAA 7",
        "VALKAMAA 8", "VALKAMAA II 1", "VALKAMAA II 2", "VALKAMAA II 3",
        "VALKAMAA II 4", "VALKAMAA II 5", "KEROLA 1", "KEROLA 2",
        "KEROLA 3", "KEROLA 4", "KEROLA 5", "KEROLA 6",
        "KEROLA 7", "KEROLA 8", "KEROLA 9", "KEROLA 10",
        "KEROLA 11", "KEROLA 12", "KEROLA II 1", "KEROLA II 2",
        "KEROLA II 3", "KEROLA II 4", "KEROLA II 5", "KEROLA II 6",
        "KEROLA II 7", "KEROLA II 8", "HEIKKILÄ 2", "HEIKKILÄ 3",
        "HEIKKILÄ 4", "HEIKKILÄ 5", "HEIKKILÄ 6", "HEIKKILÄ 7",
        "HEIKKILÄ 8", "HEIKKILÄ 9", "HEIKKILÄ 10", "HEIKKILÄ 11",
        "HEIKKILÄ 12", "JÄRVI 1", "JÄRVI 2", "JÄRVI 3",
        "JÄRVI 4", "JÄRVI 5", "JÄRVI 6", "JÄRVI 7",
        "JÄRVI 8", "JÄRVI 9", "JÄRVI 10", "JÄRVI 11",
        "JÄRVI 12", "JÄRVI 13", "JÄRVI II 1", "JÄRVI II 2",
        "JÄRVI II 3", "PORKO 1", "PORKO 2", "PORKO 3",
        "PORKO 4", "PORKO 5", "PORKO 6", "ISO-RIMMI 1",
        "ISO-RIMMI 2", "ISO-RIMMI 3", "ISO-RIMMI 4", "ISO-RIMMI 5",
        "ISO-RIMMI 6", "ISO-RIMMI 7", "ISO-RIMMI 8", "ISO-RIMMI 9",
        "ISO-RIMMI 10", "ISO-RIMMI 11", "ISO-RIMMI 12", "ISO-RIMMI 13",
        "ISO-RIMMI 14", "VÄHÄ-RIMMI 1", "VÄHÄ-RIMMI 2", "VÄHÄ-RIMMI 3",
        "VÄHÄ-RIMMI 4", "VÄHÄ-RIMMI 5", "VÄHÄ-RIMMI 6", "VÄHÄ-RIMMI 7",
        "VÄHÄ-RIMMI 8", "VÄHÄ-RIMMI 9", "VÄHÄ-RIMMI 10", "VÄHÄ-RIMMI 11",
        "LUOTO 1", "LUOTO 2", "LUOTO 3", "LUOTO 4",
        "LUOTO 5", "LUOTO 6", "LUOTO 7", "LUOTO 8",
        "LUOTO 9", "LUOTO 10", "LUOTO 11", "RAUTIO 1",
        "RAUTIO 2", "RAUTIO 3", "RAUTIO 4", "RAUTIO 5",
        "RAUTIO 6", "JUNKKILA 1", "JUNKKILA 2", "JUNKKILA 3",
        "JUNKKILA 4", "JUNKKILA 5", "JUNKKILA 6", "JUNKKILA 7",
        "JUNKKILA 8", "JUNKKILA 9", "JUNKKILA 10", "JUNKKILA 11",
        "HEIKKINIEMI 1", "HEIKKINIEMI 2", "HEIKKINIEMI 3", "HEIKKINIEMI 4",
        "HEIKKINIEMI 5", "HEIKKINIEMI 6", "HEIKKINIEMI 7", "HEIKKINIEMI 8",
        "HEIKKINIEMI 9", "HEIKKINIEMI 10", "HEIKKINIEMI 11", "HEIKKINIEMI 12",
        "HEIKKINIEMI 13", "PORRI 1", "PORRI 2", "PORRI 4",
        "PORRI 7", "PORRI 8", "PORRI 9", "PORRI 10",
        "PORRI 15", "PORRI 16", "PORRI 17", "MAAJÄRVI 1",
        "MAAJÄRVI 2", "MAAJÄRVI 3", "MAAJÄRVI 4", "MAAJÄRVI 5",
        "MAAJÄRVI 6", "GRANÖ 1", "GRANÖ 2", "GRANÖ 3",
        "GRANÖ 4", "GRANÖ 5", "GRANÖ 6", "PUOTINIEMI 1",
        "PUOTINIEMI 2", "PUOTINIEMI 3", "PUOTINIEMI 4", "PUOTINIEMI 5",
        "PUOTINIEMI 6", "PUOTINIEMI 7", "PUOTINIEMI 8", "PUOTINIEMI 9",
        "RIIPPA 1", "RIIPPA 2", "RIIPPA 3", "RIIPPA 4",
        "RIIPPA 5", "RIIPPA 6", "RIIPPA 7", "RIIPPA 8",
        "RIIPPA 9", "RIIPPA 10", "RIIPPA 11", "RIIPPA II 1",
        "RIIPPA II 2", "RIIPPA II 3", "RIIPPA II 4", "KREKILÄ 1",
        "KREKILÄ 2", "KREKILÄ 3", "KREKILÄ 4", "KREKILÄ 5",
        "KREKILÄ 6", "KREKILÄ 7", "KREKILÄ 8", "KREKILÄ 9",
        "KREKILÄ 10", "KREKILÄ 11", "KREKILÄ 12", "KREKILÄ 13",
        "KREKILÄ 14", "KREKILÄ 15", "KREKILÄ 16", "KREKILÄ II 1",
        "KREKILÄ II 2", "KREKILÄ II 3", "KREKILÄ II 4", "KREKILÄ II 5",
        "SUONPERÄ 1", "SUONPERÄ 2", "SUONPERÄ 3", "SUONPERÄ 4",
        "SUONPERÄ 5", "SUONPERÄ 7", "SUONPERÄ 8", "SUONPERÄ 9",
        "SUONPERÄ 10", "SUONPERÄ 11", "SUONPERÄ 12", "SUONPERÄ II 1",
        "SUONPERÄ II 2", "SUONPERÄ II 3", "SUONPERÄ II 4", "SUONPERÄ II 5",
        "SUONPERÄ II 6", "SUONPERÄ III 1", "SUONPERÄ III 2", "SUONPERÄ III 3",
        "SUONPERÄ III 4", "SUONPERÄ III 5", "SUONPERÄ IV 1", "SUONPERÄ IV 2",
        "SUONPERÄ IV 3", "PARPALA 1", "PARPALA 2", "PARPALA 3",
        "PARPALA 4", "PARPALA 5", "PARPALA 6", "PARPALA 7",
        "PARPALA 8", "PARPALA 9", "PARPALA 10", "PARPALA 11",
        "PARPALA 12", "PUIKKO 1", "PUIKKO 2", "PUIKKO 3",
        "PUIKKO 4", "PUIKKO 5", "PUIKKO 6", "PUIKKO 7",
        "PUIKKO 8", "PUIKKO 9", "PUIKKO 10", "PUIKKO 11",
        "PUIKKO 12", "JÄRVENAUTIO 1", "JÄRVENAUTIO 3", "JÄRVENAUTIO 4",
        "JÄRVENAUTIO 5", "AUTIO 6", "AUTIO 7", "JÄRVENAUTIO 8",
        "JÄRVENAUTIO 9", "JÄRVENAUTIO 10", "KLAPURI 1", "KLAPURI 2",
        "KLAPURI 3", "KLAPURI 4", "KLAPURI 5", "KLAPURI 6",
        "KLAPURI 7", "KLAPURI 8", "KLAPURI 9", "KLAPURI 10",
        "KLAPURI 11", "KLAPURI 12", "KLAPURI 13", "KLAPURI 14",
        "KLAPURI 15", "KLAPURI 16", "KLAPURI II 1", "KLAPURI II 2",
        "KLAPURI II 3", "KLAPURI II 4", "PALONMÄKI 1", "PALONMÄKI 2",
        "PALONMÄKI 3", "PALONMÄKI 4", "PALONMÄKI 5", "PALONMÄKI 6",
        "PALONMÄKI 7", "PALONMÄKI 8", "PALONMÄKI 9", "PALONMÄKI 10",
        "MATKALA 1", "MATKALA 2", "MATKALA 3", "MATKALA 4",
        "MATKALA 5", "MATKALA 6", "KOIVUMÄKI 1", "KOIVUMÄKI 2",
        "KOIVUMÄKI 3", "KOIVUMÄKI 4", "KOIVUMÄKI 5", "KOIVUMÄKI 6",
        "HIRVELÄ 1", "HIRVELÄ 2", "HIRVELÄ 3", "HIRVELÄ 4",
        "HIRVELÄ 5", "HIRVELÄ 6", "HIRVELÄ 7", "LUOMALA 1",
        "LUOMALA 2", "LUOMALA 3", "LUOMALA 4", "LUOMALA 5",
        "PUSKALA 1", "PUSKALA 2", "PUSKALA 3", "PUSKALA 4",
        "PUSKALA 5", "PUSKALA 6", "KOIVUSALO 1", "KOIVUSALO 2",
        "KOIVUSALO 3", "KOIVUSALO 4", "KOIVUSALO 5", "KOIVUSALO 6",
        "TIILIMÄKI 1", "TIILIMÄKI 2", "TIILIMÄKI 3", "TIILIMÄKI 4",
        "PETÄJÄNSALO 1", "PETÄJÄNSALO 2", "PETÄJÄNSALO 3", "PETÄJÄNSALO 4",
        "PETÄJÄNSALO 5", "PETÄJÄNSALO 6", "PETÄJÄNSALO 7", "PETÄJÄNSALO 8",
        "KUKKONMÄKI 1", "KUKKONMÄKI 2", "KUKKONMÄKI 3", "KUKKONMÄKI 4",
        "KUKKONMÄKI 5", "KOIVUSALO 7", "PERTUNMÄKI 1", "PERTUNMÄKI 2",
        "PERTUNMÄKI 3", "PERTUNMÄKI 4", "PERTUNMÄKI 5", "PERTUNMÄKI 6",
        "KROGBACKA 1", "KROGBACKA 2", "KROGBACKA 3", "KROGBACKA 4",
        "KROGBACKA 5", "KROGBACKA 6", "SALMI 1", "SALMI 2",
        "SALMI 3", "SALMI 4", "JÖRANSBACKA 1", "JÖRANSBACKA 2",
        "JÖRANSBACKA 3", "TIKANOJA 1", "TIKANOJA 2", "TIKANOJA 3",
        "HAUTAMÄKI 1", "HAUTAMÄKI 2", "HAUTAMÄKI 3", "HAUTAMÄKI 4",
        "HAUTAMÄKI 5", "HAUTAMÄKI 6", "KÄSKOSKI 1", "KÄSKOSKI 2",
        "KÄSKOSKI 3", "KÄSKOSKI 4", "KÄSKOSKI 5", "KÄSKOSKI 6",
        "KÄSKOSKI 7", "KORPI 2B", "KALSIOMÄKI 4", "KALSIOMÄKI 5",
        "KALSIOMÄKI 6", "MOISIONMÄKI 5", "MOISIONMÄKI 6", "MOISIONMÄKI 7",
        "HEIKINMÄKI 1", "HEIKINMÄKI 2", "HEIKINMÄKI 3", "HEIKINMÄKI 4",
        "HEIKINMÄKI 5", "HEIKINMÄKI 6", "HEIKINMÄKI 7", "HEIKINMÄKI 8",
        "MYLLYOJA 1", "MYLLYOJA 2", "MYLLYOJA 3", "MYLLYOJA 4",
        "MYLLYOJA 5", "MYLLYOJA 6", "MYLLYOJA 7", "KUUSIMÄKI 1",
        "KUUSIMÄKI 2", "KUUSIMÄKI 3", "KUUSIMÄKI 4", "KUUSIMÄKI 5",
        "KUUSIMÄKI 6", "RUMPALI 1", "RUMPALI 2"
    ]

    // MARK: - Secondary Storage (Sets for O(1) lookups)
    
    private static let validFamilyIdSet: Set<String> = Set(validFamilyIds)
    private static let uppercasedFamilyIdSet: Set<String> = Set(validFamilyIds.map { $0.uppercased() })
    private static let normalizedValidFamilyIds: Set<String> = Set(validFamilyIds.map { normalize($0) })
    
    // MARK: - Lookup Dictionary (for O(1) index finding)
    
    private static let familyIdToIndex: [String: Int] = {
        var dict = [String: Int]()
        for (index, familyId) in validFamilyIds.enumerated() {
            dict[familyId.uppercased()] = index
        }
        return dict
    }()
    
    // MARK: - Public Helper
    
    public static func normalize(_ s: String) -> String {
        let trimmed = s.trimmingCharacters(in: .whitespacesAndNewlines)
        let collapsed = trimmed.replacingOccurrences(of: "\\s+", with: " ", options: .regularExpression)
        return collapsed.folding(options: [.caseInsensitive, .diacriticInsensitive], locale: .current)
    }
    
    // MARK: - Public API (All O(1) operations!)
    
    static func isValid(familyId: String) -> Bool {
        return uppercasedFamilyIdSet.contains(familyId.uppercased())
    }
    
    static func indexOf(familyId: String) -> Int? {
        return familyIdToIndex[familyId.uppercased()]
    }
    
    static func familyAt(index: Int) -> String? {
        guard index >= 0 && index < validFamilyIds.count else { return nil }
        return validFamilyIds[index]
    }
    
    static func nextFamilyAfter(_ familyId: String) -> String? {
        guard let currentIndex = indexOf(familyId: familyId) else { return nil }
        return familyAt(index: currentIndex + 1)
    }
    
    static func previousFamilyBefore(_ familyId: String) -> String? {
        guard let currentIndex = indexOf(familyId: familyId) else { return nil }
        return familyAt(index: currentIndex - 1)
    }
    
    static var count: Int {
        return validFamilyIds.count
    }
    
    static func isFirst(_ familyId: String) -> Bool {
        return indexOf(familyId: familyId) == 0
    }
    
    static func isLast(_ familyId: String) -> Bool {
        guard let index = indexOf(familyId: familyId) else { return false }
        return index == validFamilyIds.count - 1
    }
    
    // Batch operations for caching
    static func familiesAfter(_ familyId: String, maxCount: Int = Int.max) -> [String] {
        guard let currentIndex = indexOf(familyId: familyId) else { return [] }
        let startIndex = currentIndex + 1
        guard startIndex < validFamilyIds.count else { return [] }
        let endIndex = min(startIndex + maxCount, validFamilyIds.count)
        return Array(validFamilyIds[startIndex..<endIndex])
    }
}
